### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by friishon** [xXKeyleXx/MyPet#978] opened 2017-02-22 20:42 UTC
hi, can you add this?
furnance: consume coak, pet can cooking things but need coak
anvil: consume iron lingot
enchant table: consume lapislazuli
crafter table, consume wood
brewing_stand consume diamond to use and the items to make the potions
pets need have all the live to use this options
please think about it and sorry for my bad english, i'm from spain

**Comment by xXKeyleXx** [comment] 2017-02-23 10:43
duplicate of #816

**Closed by xXKeyleXx** 2017-02-23 10:43 UTC
Labels: Duplicate
