### ISSUE TITLE
Can not release Pets if they have a colored name

### ISSUE THREAD

**Issue by Extreme21** [xXKeyleXx/MyPet#591] opened 2015-12-23 17:59 UTC
When you click to confirm the pet release, if the pet name is coloured, you can not release it, and it repeats: "Click in the name to confirm."

Thanks in advance.

**Comment by xXKeyleXx** [comment] 2015-12-23 20:56
Could you give me the name of your pet. It works fine for me so I need more info to reproduce the problem.

**Comment by ExtremoDuro** [comment] 2015-12-23 21:01
/petname <red> name

When I click in the chat to confirm the release, it repeats the message, and the pet is not released.

I can make a video if you want

**Comment by xXKeyleXx** [comment] 2015-12-23 21:04
No it's OK I can reproduce the error now. The problem is the space between "<red> name".

**Comment by xXKeyleXx** [comment] 2015-12-23 21:10
should be fixed in the latest build. The latest build may be unstable because of big changes so make backups beforehand.

**Closed by xXKeyleXx** 2015-12-23 21:10 UTC
Labels: Unconfirmed Bug
