### ISSUE TITLE
MyPet plugin pet not getting exp

### ISSUE THREAD

**Issue by ExOhGaming** [xXKeyleXx/MyPet#1080] opened 2017-12-13 18:32 UTC
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
spigot 1.12/1.12.2
**MyPet Build/Version:**
MyPet 2.3.2
**Do you use the premium version? (this wont change anything for you)**
no
**What is the expected result?**
i tried to level up my pet
**What happens instead of that?**
my pet received no exp and dident level from any mob it killed i had combat skill tree chosen at the time
**Error:**

**Comment by xXKeyleXx** [comment] 2017-12-13 20:10
It might be a duplicate of #1051

**Closed** 2018-01-08 18:31 UTC
