### ISSUE TITLE
Some players cannot tame a pet even with perms .. 

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#576] opened 2015-11-30 23:27 UTC
Only been getting reports of it since the latest dev build .. I'm confused as I can tame the pets, but my player after recieving the permission could not .. I made sure he had no pet active amd i watched him leash punch the blaze til it died .. Taming failed.

**Comment by tara81** [comment] 2015-11-30 23:29
Build 714

**Comment by xXKeyleXx** [comment] 2015-11-30 23:49
Do you use GriefPrevention?

**Comment by Belinda13na** [comment] 2015-12-02 18:20
We still can't tame pets either. 
I told the owner to update to todays latest one. Will let you know if fixed :)

**Comment by tara81** [comment] 2015-12-03 00:18
GriefPrevention: false

so no.

It used to work before. I am very confused.

**Comment by tara81** [comment] 2015-12-03 00:31
I am going to attempt a revert and check it out .

**Comment by xXKeyleXx** [comment] 2015-12-03 09:19
My problem is that it works fine for me :/ and what I can't reproduce is very hard to fix... Did you tried build 715? if no try it, if yes please run the "/petadmin ticket" and upload the "plugins/MyPet/ticket.zip" file for me.

**Comment by tara81** [comment] 2015-12-03 15:22
Okay the issue is for some odd reason, individual permissions are not working in 714 , however, group permissions are working in 714.

Now i reverted back to a 6xx version and it works again. I am throughly confused on why one type of permission is working but not the other .. 

http://www.mediafire.com/download/61mzd098f7c414r/MyPet.jar < - version that individual permissions work.. 

I will test 715 tomorrow

**Comment by tara81** [comment] 2015-12-03 15:23
I suggest testing individual permissions

**Comment by xXKeyleXx** [comment] 2015-12-03 15:30
What permission plugin do you use?

**Comment by tara81** [comment] 2015-12-04 20:17
bpermissions, I tried 715 and still players cannot tame with individual permissions

**Comment by tara81** [comment] 2015-12-04 20:17
It makes no sense if it works in this 6xx version , how can it be my permissions, know what I mean ;(

**Comment by tara81** [comment] 2015-12-05 02:51
Here is the tickets.zip from 715
http://www.mediafire.com/download/2r8djcqpye66xeo/ticket.zip

**Comment by xXKeyleXx** [comment] 2015-12-05 11:11
It makes no sense at all... Do you know which exact build introduced this problem?

**Comment by tara81** [comment] 2015-12-05 16:04
No =( Because I only changed a few times when i noticed there were issues

**Comment by xXKeyleXx** [comment] 2015-12-05 17:15
No, that's the reason why I can't fix it. It works fine for me =( The last thing you could do is to ZIP your whole server, upload it anywhere and send me the download link per email at admin@keyle.de so I have the real environment where I can replicate it.

**Comment by xXKeyleXx** [comment] 2015-12-05 23:34
Well then you have to find out by yourself which build caused the problem. I can't fix what I can't reproduce.

**Comment by tara81** [comment] 2015-12-07 20:38
So i found out the issue is fixed by relogging. I have no idea why ........... It is happening in every single version for me... I am so confused ... Maybe it is permissions issue .. https://youtu.be/qrJaT-UOaR8

**Comment by tara81** [comment] 2015-12-07 20:40
Sorry for the poor video quality. I am not good at recording =(

**Comment by xXKeyleXx** [comment] 2015-12-09 15:12
I think so too, especially when it works after relogging. Have you tried the latest beta build of bPerm? Maybe it's fixed there.

**Comment by tara81** [comment] 2015-12-09 21:01
I think it started happening after i started using the latest build of
bperms.  It took me awhile to figure out because I already have all perms,
my players only started complaining recently.  Sadly I must stay on that
lattest build because it fixes a major lag issue.

**Comment by xXKeyleXx** [comment] 2015-12-09 22:39
Can I close this?

**Comment by tara81** [comment] 2015-12-11 12:05
Well I dont know, the perms guy says he has a feeling it is mypet... But He hasn't responded in awhile or tested it yet so IDk

**Comment by xXKeyleXx** [comment] 2015-12-11 12:07
You said it works after relogging so I'm very certain that it is not a problem with MyPet because if you don't have a pet already there is nothing that changes after relogging.

**Comment by xXKeyleXx** [comment] 2015-12-11 12:08
I would really like to solve this problem so I can upload a new version to BukkitDev/Spigot forums.

**Comment by xXKeyleXx** [comment] 2015-12-14 22:44
Anything new?

**Comment by tara81** [comment] 2015-12-14 23:18
The bperms guy hasn't responded. Sorry.  Still waiting. If u want u can close this and Ill request it to be opened if I hear news it's not permissions.

**Comment by xXKeyleXx** [comment] 2015-12-14 23:24
Nah, I will keep it open until it's resolved.

**Comment by tara81** [comment] 2015-12-20 16:31
Rymate finally agrees its bpermissions issue. U can close =)

rymate1234
3 hours, 33 minutes ago - 0 likes Like

@tcarey2015: Go

yeah I found that bug whilst testing a different fix, I'll work on fixing it either today or tomorrow

**Comment by xXKeyleXx** [comment] 2015-12-20 17:53
nice :D

**Closed by xXKeyleXx** 2015-12-20 17:53 UTC
