### ISSUE TITLE
Lag issue no idea

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#637] opened 2016-02-12 21:23 UTC
I have been using this plugin without any issues for the past month.  Suddenly today, it started lagging my server badly. CPU usage went to 100% then tps down to 3.

Here is my timings.

I do not know how or why this is happening, there are no errors.

http://timings.aikar.co/?url=15029523

**Comment by xXKeyleXx** [comment] 2016-02-12 21:39
MyPet 1.2.2 O.o why are you still on that old version?
Besides that, have you tried to disable some SaveOn* options in the config.
How many pets are on your server?

**Comment by tara81** [comment] 2016-02-12 22:04
Well , I try to wait to update unless its critical , because, sometimes your newer versions get bugs and kinks in it . How do I tell how mnay pets are on my server?  After making this post, I updated to the latest, no issues yet =)

**Comment by xXKeyleXx** [comment] 2016-02-12 22:05
It say the amount when the plugin loads.

**Comment by tara81** [comment] 2016-02-12 22:08
[16:37:43] [Server thread/INFO]: [MyPet] Enabling MyPet v1.2.8
[16:37:43] [Server thread/WARN]: java.io.FileNotFoundException: plugins/MyPet/pet-config.yml (No such file or directory)
[16:37:43] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[16:37:43] [Server thread/WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[16:37:43] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[16:37:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:167)
[16:37:43] [Server thread/WARN]: 	at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:223)
[16:37:43] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:150)
[16:37:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:37:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:37:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:37:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[16:37:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[16:37:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[16:37:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[16:37:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[16:37:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[16:37:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:561)
[16:37:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:37:44] [Server thread/INFO]: [MyPet] 6419 pet(s) loaded
[16:37:44] [Server thread/INFO]: [MyPet] version 1.2.8-b805 ENABLED

**Comment by tara81** [comment] 2016-02-12 22:08
I guess you changed where the mypet config goes, i will have to redo it?

**Comment by tara81** [comment] 2016-02-12 22:09
There is config and pet-config.

**Comment by xXKeyleXx** [comment] 2016-02-12 22:19
You should use the Spigot page from now on when you want updates ;)
https://www.spigotmc.org/resources/mypet.12725/
Bukkitdev hasn't approved the latest version yet.

pet-config.yml is just the MyPet.Pets node from the main config but I moved them to make the main config shorter. Copy and paste it over and you are done.

**Comment by tara81** [comment] 2016-02-13 00:30
I don't get it . both configs look exactly the same to me. Which one do I configure?

Also the lag issue has not stopped.
PlayerListener::onPlayerQuit(PlayerQuitEvent)

6419 pets .

**Comment by xXKeyleXx** [comment] 2016-02-13 10:54
1. install 1.2.9
2. delete the pet-config.yml and let the plugin generate it again
3. understand which config options are in the new pet-config.yml ->  `MyPet.Pets`
4. copy everything under `MyPet.Pets` from the config.yml to the pet-config.yml
5. delete the `MyPet.Pets` node from the config.yml

Wow 6419 pets xD this explains why your server is lagging like hell when a player quits xD
It has to generate the whole NBT structure everytime a player quits and that for more than 6k pets...

You should consider using the /petadmin cleanup command (https://mypet.keyle.de/doku.php?id=en:commands) or switch to MyPet-Premium which has MySQL support.

**Comment by tara81** [comment] 2016-02-13 16:42
WOW u got sql support? I asked u for that ages ago :dancer: 
Awesome ! Where do i get it ;D

**Comment by tara81** [comment] 2016-02-13 16:55
ok i found the premium on spigot, ty for finally doing thatr ! I hope it helps =(

**Comment by tara81** [comment] 2016-02-13 17:12
I dont understand 3-4 . mypets.pets when I open it in notepad ++ isnt in english . It has a ton of weird characters. I cannot find a mypets.pet node in the config.yml.

**Comment by xXKeyleXx** [comment] 2016-02-13 17:13
give me your config.yml and I will do it for you :P

**Comment by tara81** [comment] 2016-02-13 17:15
wow thanks. I will remove my sql password first.

**Comment by tara81** [comment] 2016-02-13 17:16
http://www.mediafire.com/download/vh97uja8mqyi67x/config.yml

**Comment by xXKeyleXx** [comment] 2016-02-13 17:23
This looks like a fresh generated config or you did step 5 before sending me the config xD

**Comment by tara81** [comment] 2016-02-13 17:24
I never deleted the node

**Comment by tara81** [comment] 2016-02-13 17:24
I couldnt see it in order to delete it .

**Comment by xXKeyleXx** [comment] 2016-02-13 17:25
oops my bad xD opened my config xD

**Comment by tara81** [comment] 2016-02-13 17:25
Might be fresh i dont know, I am very confused.

**Comment by tara81** [comment] 2016-02-13 17:25
haha k

**Comment by tara81** [comment] 2016-02-13 17:26
Im trying to convert to sql since i just got the premium. After its converted , do i remove the convert from: 'NBT' back to '' ? also for the password for sql do i put it in the brackets '' or remove them completely?

**Comment by tara81** [comment] 2016-02-13 17:29
Oh and can I have 2 minecraft players with the pet particles? Can they turn it on and off?

Names :1.  Exaltations and 2. benstevens99

**Comment by tara81** [comment] 2016-02-13 17:33
Will shield and pet flying be available in the SkilltreeCreator - Tool

**Comment by xXKeyleXx** [comment] 2016-02-13 17:41
1. It will remove the NBT automatically so it will convert the data only once.
2. No they can not turn it on/off
3. the premium version has them in the SkilltreeCreator

[configs.zip](https://github.com/xXKeyleXx/MyPet/files/129305/configs.zip)

**Comment by tara81** [comment] 2016-02-13 17:43
Thanks a lot =D

**Comment by tara81** [comment] 2016-02-13 17:45
Oh u were splitting the config to show the pet list , now i see what u did there !

**Comment by tara81** [comment] 2016-02-13 17:45
When will the 2 players Exaltations and benstevens99 have particles on their pet?

**Comment by xXKeyleXx** [comment] 2016-02-13 17:46
Yeah I didn't know how to explain it properly xD
They should already have them (on their next login)

**Comment by tara81** [comment] 2016-02-13 17:47
yay thank you !  :D cant wait to see it ! They are my top donators.

**Comment by xXKeyleXx** [comment] 2016-02-13 17:47
:D

can I close this or do you have any questions?

**Comment by tara81** [comment] 2016-02-13 17:47
I remember way back I asked for a pokemon like dueling system, and you eventually declined it.  If i offered for you to add it to the premium or regular for $50 usd would u do it?

**Comment by xXKeyleXx** [comment] 2016-02-13 17:49
I still think that it doesn't fit into the plugin and/or Minecrafts combat system so my answer is still not sorry.

**Comment by tara81** [comment] 2016-02-13 17:50
boo ok. Yes u may close it.

**Comment by xXKeyleXx** [comment] 2016-02-13 17:50
Thank you sir xD

**Closed by xXKeyleXx** 2016-02-13 17:50 UTC

**Comment by xXKeyleXx** [comment] 2016-02-13 17:52
btw you are the first who claimed the 2 particle pets xD

**Comment by tara81** [comment] 2016-02-13 18:21
well I lost all my pets. This sql database doesnt work .

**Comment by xXKeyleXx** [comment] 2016-02-13 18:23
Could you be a bit more specific? What doesn't work?

**Comment by tara81** [comment] 2016-02-13 18:29
REverts arent working NOTHING is working

**Comment by tara81** [comment] 2016-02-13 18:29
1.2.9 kills the pet database from what i can tell after u attempt a SQL convert.

**Comment by xXKeyleXx** [comment] 2016-02-13 18:30
could you upload your pets file so I can analyze what the problem is?

**Comment by tara81** [comment] 2016-02-13 18:30
I even replace mypets.pet with my old one and it changes into another file every time, 1/3rd of the size

**Comment by tara81** [comment] 2016-02-13 18:31
http://www.mediafire.com/download/xgocab30blb14ds/My.Pets

**Comment by tara81** [comment] 2016-02-13 18:37
:(

**Comment by xXKeyleXx** [comment] 2016-02-13 18:38
still converting.... :/

**Comment by tara81** [comment] 2016-02-13 18:38
upon every restart, the file size of my.pets gets changed ..

**Comment by tara81** [comment] 2016-02-13 18:39
Wow, U know, I dont even have that big of a player base.  30-50 players. I hate to see the servers with 1000's of players.

**Comment by xXKeyleXx** [comment] 2016-02-13 18:41
While my server is still converting, what is your MySQL server version and database collation?

**Comment by xXKeyleXx** [comment] 2016-02-13 18:45
Well it worked fine for me my database has 6,440 pets and 4,468 players. Exact the same values you have in your My.Pets file....

**Comment by xXKeyleXx** [comment] 2016-02-13 18:46
Here is an SQL export I did: https://dl.dropboxusercontent.com/u/23957620/crap/mypet.zip

**Comment by tara81** [comment] 2016-02-13 18:49
Apache/2.4.7 (Ubuntu)
    Database client version: libmysql - 5.5.44
    PHP extension: mysqli Documentation

**Comment by xXKeyleXx** [comment] 2016-02-13 18:51
is there anything in the logfiles (serverlog or MyPet log) that could point me to the problem?

**Comment by tara81** [comment] 2016-02-13 18:52
i will upload the log file after rebooting with the import of the mypet.zip u gave me if it doesnt work

**Comment by tara81** [comment] 2016-02-13 18:54
omg it worked. Thank u thank u thank u ! It wouldnt convert for me ! 

Should I still do admin cleanup if im using sql ?

**Comment by tara81** [comment] 2016-02-13 18:55
I can't send you the log file of the pets because i overwrote it, in attempts to revert to get the pets back .. nothing was working it was so strange.

**Comment by xXKeyleXx** [comment] 2016-02-13 18:56
I would have been nice to know what the problem was >.<

Yes you can still do the cleanup command ;)

**Comment by tara81** [comment] 2016-02-13 19:01
thank god the pets are back. Thank god. Thank u ! ahhh. Players love the pets so much they freak out when their pet is gone.
