### ISSUE TITLE
Bukkit-Version:

### ISSUE THREAD

**Issue by SkyceDE** [xXKeyleXx/MyPet#1012] opened 2017-06-18 09:40 UTC
**Bukkit/Spigot/Bungee Build/Version:**
Spigot: version 1.8.8-R0.1-Snapshot
BungeeBuild: BungeeCord-Bootstrap:1.12-Snapshot

**MyPet Build/Version:**
2.3.4

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
When you open the shop (/petshop), then the PetShop open.

**What happens instead of that?**
The PetShop opens very slow! More than 5 Seconds, sometimes more then 10. The hole Server is hanging trough this time.

**Error:**
No error in the console.

**Comment by xXKeyleXx** [comment] 2017-06-18 11:06
Does this happen too when you use the /petswitch command? Could you append your pet-shops.yml please.

**Comment by SkyceDE** [comment] 2017-06-18 14:27
No, the /petswitch command opens directly the storage.

The pet-shops.yml is the default pet-shops,yml

**Comment by xXKeyleXx** [comment] 2017-06-18 14:30
Could you please start the timings, execute the command and stop the timings?
https://www.spigotmc.org/wiki/timings/

**Comment by SkyceDE** [comment] 2017-06-18 14:50
https://timings.spigotmc.org/?url=0

It only gives me this link in the chat...

**Comment by xXKeyleXx** [comment] 2017-06-18 14:56
hm.... it doesn't seems to work with such an old Spigot version anymore :/
Then use the "/timings report" command instead and attach the generated txt file.

**Comment by SkyceDE** [comment] 2017-06-18 15:50
[timings.txt](https://github.com/xXKeyleXx/MyPet/files/1083184/timings.txt)

**Comment by xXKeyleXx** [comment] 2017-06-20 19:17
Ok the timings told me that it really lagged but nothing more xD

Hm... what is your economy setup? Does your economy plugin uses MySQL?

**Comment by SkyceDE** [comment] 2017-06-23 16:09
Yeah, we use iConomy Recreation with MySQL

**Comment by xXKeyleXx** [comment] 2017-06-23 16:11
The problem is that the plugin checks if the player can buy for every pet in the store and every check dies a MySQL query and that is what makes it take so long. I guess I have to change it then to address the problem...

**Comment by SkyceDE** [comment] 2017-06-23 16:12
Okay very nice!
You contact me?

**Comment by xXKeyleXx** [comment] 2017-06-23 16:13
I will close this ticket :P

**Comment by xXKeyleXx** [comment] 2017-06-23 16:38
Done. https://mypet-plugin.de/download

**Closed by xXKeyleXx** 2017-06-23 16:38 UTC
Labels: Bug (Unchecked)
